export const roleTemplates = {
  Admin: {
    dashboard: { view: true },
    sales: { view: true, create: true, edit: true, delete: true },
    salesOrder: { view: true, create: true, edit: true, delete: true },
    purchase: { view: true, create: true, edit: true, delete: true },
    production: { view: true, create: true, edit: true, delete: true },
    beam: { view: true, create: true, edit: true, delete: true },
    inventory: { view: true, edit: true, delete: true },
    qc: { view: true, approve: true, reject: true },
    accounts: { view: true, createInvoice: true, manageLedger: true },
    payroll: { view: true, generate: true, manage: true },
    jobWork: { view: true, issue: true, receive: true },
    dispatch: { view: true, create: true, edit: true, delete: true },
    reports: { view: true, generate: true, export: true },
    settings: { manageUsers: true, manageRoles: true },
  },
  ProductionManager: {
    dashboard: { view: true },
    sales: { view: false, create: false, edit: false, delete: false },
    salesOrder: { view: true, create: false, edit: true, delete: false },
    purchase: { view: true, create: false, edit: false, delete: false },
    production: { view: true, create: true, edit: true, delete: false },
    beam: { view: true, create: true, edit: true, delete: false },
    inventory: { view: true, edit: false, delete: false },
    qc: { view: true, approve: false, reject: false },
    accounts: { view: false, createInvoice: false, manageLedger: false },
    payroll: { view: false, generate: false, manage: false },
    jobWork: { view: true, issue: true, receive: true },
    dispatch: { view: true, create: false, edit: false, delete: false },
    reports: { view: true, generate: true, export: false },
    settings: { manageUsers: false, manageRoles: false },
  },
  SalesManager: {
    dashboard: { view: true },
    sales: { view: true, create: true, edit: true, delete: false },
    salesOrder: { view: true, create: true, edit: true, delete: false },
    purchase: { view: false, create: false, edit: false, delete: false },
    production: { view: true, create: false, edit: false, delete: false },
    beam: { view: false, create: false, edit: false, delete: false },
    inventory: { view: true, edit: false, delete: false },
    qc: { view: true, approve: false, reject: false },
    accounts: { view: false, createInvoice: false, manageLedger: false },
    payroll: { view: false, generate: false, manage: false },
    jobWork: { view: false, issue: false, receive: false },
    dispatch: { view: true, create: true, edit: true, delete: false },
    reports: { view: true, generate: true, export: false },
    settings: { manageUsers: false, manageRoles: false },
  },
  PurchaseManager: {
    dashboard: { view: true },
    sales: { view: false, create: false, edit: false, delete: false },
    salesOrder: { view: false, create: false, edit: false, delete: false },
    purchase: { view: true, create: true, edit: true, delete: false },
    production: { view: false, create: false, edit: false, delete: false },
    beam: { view: false, create: false, edit: false, delete: false },
    inventory: { view: true, edit: true, delete: false },
    qc: { view: true, approve: false, reject: false },
    accounts: { view: false, createInvoice: false, manageLedger: false },
    payroll: { view: false, generate: false, manage: false },
    jobWork: { view: false, issue: false, receive: false },
    dispatch: { view: false, create: false, edit: false, delete: false },
    reports: { view: true, generate: true, export: false },
    settings: { manageUsers: false, manageRoles: false },
  },
  QCOfficer: {
    dashboard: { view: true },
    sales: { view: false, create: false, edit: false, delete: false },
    salesOrder: { view: false, create: false, edit: false, delete: false },
    purchase: { view: false, create: false, edit: false, delete: false },
    production: { view: true, create: false, edit: false, delete: false },
    beam: { view: false, create: false, edit: false, delete: false },
    inventory: { view: true, edit: false, delete: false },
    qc: { view: true, approve: true, reject: true },
    accounts: { view: false, createInvoice: false, manageLedger: false },
    payroll: { view: false, generate: false, manage: false },
    jobWork: { view: false, issue: false, receive: false },
    dispatch: { view: false, create: false, edit: false, delete: false },
    reports: { view: true, generate: true, export: false },
    settings: { manageUsers: false, manageRoles: false },
  },
  StoreIncharge: {
    dashboard: { view: true },
    sales: { view: false, create: false, edit: false, delete: false },
    salesOrder: { view: false, create: false, edit: false, delete: false },
    purchase: { view: true, create: false, edit: false, delete: false },
    production: { view: true, create: false, edit: false, delete: false },
    beam: { view: true, create: false, edit: false, delete: false },
    inventory: { view: true, edit: true, delete: false },
    qc: { view: true, approve: false, reject: false },
    accounts: { view: false, createInvoice: false, manageLedger: false },
    payroll: { view: false, generate: false, manage: false },
    jobWork: { view: true, issue: true, receive: true },
    dispatch: { view: true, create: false, edit: false, delete: false },
    reports: { view: true, generate: true, export: false },
    settings: { manageUsers: false, manageRoles: false },
  },
  AccountsOfficer: {
    dashboard: { view: true },
    sales: { view: true, create: false, edit: false, delete: false },
    salesOrder: { view: true, create: false, edit: false, delete: false },
    purchase: { view: true, create: false, edit: false, delete: false },
    production: { view: false, create: false, edit: false, delete: false },
    beam: { view: false, create: false, edit: false, delete: false },
    inventory: { view: true, edit: false, delete: false },
    qc: { view: false, approve: false, reject: false },
    accounts: { view: true, createInvoice: true, manageLedger: true },
    payroll: { view: false, generate: false, manage: false },
    jobWork: { view: false, issue: false, receive: false },
    dispatch: { view: true, create: false, edit: false, delete: false },
    reports: { view: true, generate: true, export: true },
    settings: { manageUsers: false, manageRoles: false },
  },
  JobWorkCoordinator: {
    dashboard: { view: true },
    sales: { view: false, create: false, edit: false, delete: false },
    salesOrder: { view: false, create: false, edit: false, delete: false },
    purchase: { view: false, create: false, edit: false, delete: false },
    production: { view: true, create: false, edit: false, delete: false },
    beam: { view: false, create: false, edit: false, delete: false },
    inventory: { view: true, edit: true, delete: false },
    qc: { view: false, approve: false, reject: false },
    accounts: { view: false, createInvoice: false, manageLedger: false },
    payroll: { view: false, generate: false, manage: false },
    jobWork: { view: true, issue: true, receive: true },
    dispatch: { view: false, create: false, edit: false, delete: false },
    reports: { view: true, generate: true, export: false },
    settings: { manageUsers: false, manageRoles: false },
  },
};

